try:
   print(x)
except:
   print("Bu exception")

# Errorni ko'rmoqchi bolsangiz try va exceptni o'chiring !